#!/usr/bin/env bash
if [ -f ingest.log ] ; then
  cat ingest.log
fi

script=${1:-./load-events.sh}
source=${2:-/data/github/raw/}

find $source -type f \
| sort \
| time xargs -n 4 -P 6  $script \
| tee -a ingest.log 2> ingest.err
