#!/usr/bin/env bash

mkdir -p /data/github/processed/
target=/data/github/processed/$(basename $1)

psql -X <<EOF
CREATE TEMP TABLE raw (data jsonb);
\COPY raw FROM PROGRAM 'cat $1 | gzip -d | grep -v "\\u0000"' WITH (format 'csv', quote e'\x01', delimiter e'\x02', escape e'\x01')
\COPY (SELECT (data->'repo'->>'id')::bigint, data FROM raw WHERE data->'repo'->>'id' IS NOT NULL) TO PROGRAM 'gzip > $target'
EOF
